import { Briefcase, Building2, MapPin } from "lucide-react";

export const jobs = [
  {
    id: 1,
    title: "Senior Frontend Developer",
    company: "Innovate Inc.",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$120k - $150k",
    posted: "2 days ago",
    logo: "https://picsum.photos/seed/logo1/100/100",
    tags: ["React", "TypeScript", "Remote"],
    status: "applied",
    source: "Direct",
  },
  {
    id: 2,
    title: "Product Manager",
    company: "Tech Solutions",
    location: "New York, NY",
    type: "Full-time",
    salary: "$110k - $140k",
    posted: "5 days ago",
    logo: "https://picsum.photos/seed/logo2/100/100",
    tags: ["Agile", "SaaS", "Product"],
    status: "interviewing",
    source: "Direct",
  },
  {
    id: 3,
    title: "UX/UI Designer",
    company: "Creative Minds",
    location: "Austin, TX (Remote)",
    type: "Contract",
    salary: "$80/hr",
    posted: "1 week ago",
    logo: "https://picsum.photos/seed/logo3/100/100",
    tags: ["Figma", "User Research", "Mobile"],
    status: "offer",
    source: "Direct",
  },
  {
    id: 4,
    title: "Backend Engineer (Python)",
    company: "DataDriven Co.",
    location: "Chicago, IL",
    type: "Full-time",
    salary: "$130k - $160k",
    posted: "3 days ago",
    logo: "https://picsum.photos/seed/logo4/100/100",
    tags: ["Python", "Django", "AWS"],
    status: "applied",
    source: "Direct",
  },
  {
    id: 5,
    title: "DevOps Engineer",
    company: "CloudNine",
    location: "Remote",
    type: "Full-time",
    salary: "$125k - $155k",
    posted: "1 day ago",
    logo: "https://picsum.photos/seed/logo5/100/100",
    tags: ["Kubernetes", "Docker", "CI/CD"],
    status: "interviewing",
    source: "Direct",
  },
  {
    id: 6,
    title: "Data Scientist",
    company: "AI Labs",
    location: "Boston, MA",
    type: "Full-time",
    salary: "$140k - $170k",
    posted: "6 days ago",
    logo: "https://picsum.photos/seed/logo6/100/100",
    tags: ["Machine Learning", "Python", "NLP"],
    status: "rejected",
    source: "Direct",
  },
  {
    id: 7,
    title: "Mobile Developer (iOS)",
    company: "Appify",
    location: "Remote",
    type: "Full-time",
    salary: "$130k - $160k",
    posted: "4 days ago",
    logo: "https://picsum.photos/seed/logo7/100/100",
    tags: ["Swift", "iOS", "Mobile"],
    status: "applied",
    source: "Direct",
  },
  {
    id: 8,
    title: "Marketing Manager",
    company: "Growth Hackers",
    location: "Los Angeles, CA",
    type: "Full-time",
    salary: "$90k - $110k",
    posted: "10 days ago",
    logo: "https://picsum.photos/seed/logo8/100/100",
    tags: ["SEO", "Content Marketing", "Social Media"],
    status: "rejected",
    source: "Direct",
  }
];

export const externalJobs = [
    {
        id: 101,
        title: "Lead Software Engineer",
        company: "MegaCorp India",
        location: "Bengaluru, India",
        type: "Full-time",
        salary: "₹30L - ₹45L",
        posted: "1 day ago",
        logo: "https://picsum.photos/seed/extlogo1/100/100",
        tags: ["Java", "Spring Boot", "Microservices"],
        source: "Naukri.com",
    },
    {
        id: 102,
        title: "Senior Data Analyst",
        company: "Global Analytics",
        location: "Pune, India",
        type: "Full-time",
        salary: "₹18L - ₹25L",
        posted: "3 days ago",
        logo: "https://picsum.photos/seed/extlogo2/100/100",
        tags: ["SQL", "Tableau", "Python"],
        source: "Naukri.com",
    },
    {
        id: 103,
        title: "Cloud Architect",
        company: "InfraCloud",
        location: "Hyderabad, India (Remote)",
        type: "Full-time",
        salary: "₹40L - ₹60L",
        posted: "4 days ago",
        logo: "https://picsum.photos/seed/extlogo3/100/100",
        tags: ["AWS", "Azure", "Terraform"],
        source: "Naukri.com",
    },
    {
        id: 104,
        title: "Python Developer",
        company: "Fintech Gurus",
        location: "Mumbai, India",
        type: "Full-time",
        salary: "₹15L - ₹22L",
        posted: "2 days ago",
        logo: "https://picsum.photos/seed/extlogo4/100/100",
        tags: ["Python", "Flask", "Fintech"],
        source: "Naukri.com",
    },
    {
        id: 105,
        title: "Site Reliability Engineer",
        company: "E-Comm Express",
        location: "Bengaluru, India",
        type: "Full-time",
        salary: "₹22L - ₹30L",
        posted: "5 days ago",
        logo: "https://picsum.photos/seed/extlogo5/100/100",
        tags: ["SRE", "Kubernetes", "Prometheus"],
        source: "Naukri.com",
    },
    {
        id: 106,
        title: "Digital Marketing Specialist",
        company: "AdVantage Media",
        location: "Delhi, India",
        type: "Full-time",
        salary: "₹12L - ₹18L",
        posted: "1 week ago",
        logo: "https://picsum.photos/seed/extlogo6/100/100",
        tags: ["Google Ads", "Facebook Ads", "Analytics"],
        source: "Naukri.com",
    }
];

export const companies = [
  {
    id: 1,
    name: "Innovate Inc.",
    logo: "https://picsum.photos/seed/logo1/100/100",
    industry: "SaaS",
    location: "San Francisco, CA",
    rating: 4.5,
    cultureScore: 8.8,
    happinessScore: 9.2,
    interviewDifficulty: 3.5,
  },
  {
    id: 2,
    name: "Tech Solutions",
    logo: "https://picsum.photos/seed/logo2/100/100",
    industry: "Fintech",
    location: "New York, NY",
    rating: 4.2,
    cultureScore: 8.1,
    happinessScore: 8.5,
    interviewDifficulty: 4.0,
  },
  {
    id: 3,
    name: "Creative Minds",
    logo: "https://picsum.photos/seed/logo3/100/100",
    industry: "Design Agency",
    location: "Austin, TX",
    rating: 4.8,
    cultureScore: 9.5,
    happinessScore: 9.6,
    interviewDifficulty: 2.8,
  },
  {
    id: 4,
    name: "DataDriven Co.",
    logo: "https://picsum.photos/seed/logo4/100/100",
    industry: "Big Data",
    location: "Chicago, IL",
    rating: 4.1,
    cultureScore: 7.9,
    happinessScore: 8.2,
    interviewDifficulty: 4.2,
  },
  {
    id: 5,
    name: "CloudNine",
    logo: "https://picsum.photos/seed/logo5/100/100",
    industry: "Cloud Services",
    location: "Remote",
    rating: 4.6,
    cultureScore: 9.1,
    happinessScore: 9.0,
    interviewDifficulty: 3.2,
  },
  {
    id: 6,
    name: "AI Labs",
    logo: "https://picsum.photos/seed/logo6/100/100",
    industry: "Artificial Intelligence",
    location: "Boston, MA",
    rating: 4.7,
    cultureScore: 8.9,
    happinessScore: 9.3,
    interviewDifficulty: 4.5,
  },
  {
    id: 7,
    name: "MegaCorp India",
    logo: "https://picsum.photos/seed/extlogo1/100/100",
    industry: "IT Services",
    location: "Bengaluru, India",
    rating: 4.0,
    cultureScore: 7.5,
    happinessScore: 8.0,
    interviewDifficulty: 3.8,
  },
  {
    id: 8,
    name: "Global Analytics",
    logo: "https://picsum.photos/seed/extlogo2/100/100",
    industry: "Data Analytics",
    location: "Pune, India",
    rating: 4.3,
    cultureScore: 8.2,
    happinessScore: 8.5,
    interviewDifficulty: 3.9,
  }
];

export type JobStatus = "applied" | "interviewing" | "offer" | "rejected";

export const jobApplicationColumns: {
  id: JobStatus;
  title: string;
  jobs: typeof jobs;
}[] = [
  {
    id: "applied",
    title: "Applied",
    jobs: jobs.filter((j) => j.status === "applied"),
  },
  {
    id: "interviewing",
    title: "Interviewing",
    jobs: jobs.filter((j) => j.status === "interviewing"),
  },
  {
    id: "offer",
    title: "Offer",
    jobs: jobs.filter((j) => j.status === "offer"),
  },
  {
    id: "rejected",
    title: "Rejected",
    jobs: jobs.filter((j) => j.status === "rejected"),
  },
];
