// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// Your web app's Firebase configuration will be populated here by the service.
export const firebaseConfig = {
  "projectId": "studio-8612578263-b0651",
  "appId": "1:698295987721:web:e5ad285a84116d6fe112d8",
  "apiKey": "AIzaSyBupA-9j-maVpg_ODdwNsRT4YN3yQoHG2Q",
  "authDomain": "studio-8612578263-b0651.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "698295987721"
};
