// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// Your web app's Firebase configuration will be populated here by the service.
export const firebaseConfig = {};
